'use strict';

// File naming and folder taxonomy.
//
// "Tax-ready" is not a feeling about a folder; it is the property that a CPA,
// or an auditor three years from now, can locate any document from its
// metadata alone and can tell what it is without opening it. That requires the
// name to be generated by a rule rather than typed by a person.
//
// The rule here is reversible on purpose: `parseFileName(buildFileName(x))`
// returns `x`. A naming convention that cannot be parsed back is a convention
// nobody can audit, migrate, or verify.

const { LedgerError } = require('./ledger');

class TaxonomyError extends LedgerError {}

function fail(message) {
  throw new TaxonomyError(message);
}

// Two underscores separate fields; single hyphens live inside them. Neither
// character survives slugging, so the separator can never appear in a value and
// the parse stays unambiguous.
const FIELD_SEPARATOR = '__';

const DOC_TYPES = Object.freeze([
  'RECEIPT',
  'INVOICE',
  'STATEMENT',
  'CONTRACT',
  'TAXFORM',
  'PAYROLL',
  'MILEAGE',
  'LICENSE',
  'CORRESPONDENCE',
  'OTHER',
]);

// Where a document lands once filed. Keyed by doc type so filing is a lookup,
// not a judgement call made differently on a Tuesday than on a Friday.
const DOC_TYPE_FOLDERS = Object.freeze({
  RECEIPT: '02_Receipts',
  INVOICE: '03_Invoices',
  STATEMENT: '01_Statements',
  CONTRACT: '05_Contracts',
  TAXFORM: '00_Tax-Forms',
  PAYROLL: '04_Payroll',
  MILEAGE: '06_Mileage-and-Travel',
  LICENSE: '07_Licenses-and-Permits',
  CORRESPONDENCE: '08_Correspondence',
  OTHER: '09_Unsorted',
});

const NO_AMOUNT = 'NOAMT';
const NO_REFERENCE = 'NOREF';
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

/**
 * Reduce free text to a filename-safe token.
 *
 * Deliberately lossy and deliberately deterministic: "Sweetwater Sound, Inc."
 * and "sweetwater sound inc" must produce the same token, or the same vendor
 * ends up filed in two places and the year-end totals are quietly wrong.
 */
function slug(value, field, { maxLength = 48, canonicalCase = true } = {}) {
  if (typeof value !== 'string') fail(`${field} must be a string`);
  const cleaned = value
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')   // strip accents rather than dropping the letter
    .replace(/&/g, ' and ')
    .replace(/[^A-Za-z0-9]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  if (!cleaned) fail(`${field} must contain at least one alphanumeric character`);
  const trimmed = cleaned.slice(0, maxLength).replace(/-$/, '');

  // Case is noise in a vendor name and signal in a reference number, so the
  // caller says which this is. Canonical case title-cases every token, which
  // costs us acronym styling (IBM files as "Ibm") and buys us the guarantee
  // that one vendor is one token no matter who typed it or how.
  if (!canonicalCase) return trimmed;
  return trimmed
    .split('-')
    .map(token => token.charAt(0).toUpperCase() + token.slice(1).toLowerCase())
    .join('-');
}

function requireDate(value, field) {
  const text = value instanceof Date ? value.toISOString().slice(0, 10) : value;
  if (typeof text !== 'string' || !DATE_PATTERN.test(text)) {
    fail(`${field} must be a YYYY-MM-DD date`);
  }
  // Reject 2026-02-31 and friends: the calendar has to agree that the day
  // exists, or the tax year the document sorts into is a guess.
  const parsed = new Date(`${text}T00:00:00Z`);
  if (Number.isNaN(parsed.getTime()) || parsed.toISOString().slice(0, 10) !== text) {
    fail(`${field} is not a real calendar date: ${text}`);
  }
  return text;
}

/**
 * Money is carried as integer cents everywhere in this system. Floats are how
 * a reconciliation ends up eleven cents off with no explanation.
 */
function parseMoney(value, field = 'amount') {
  if (typeof value === 'number') {
    if (!Number.isInteger(value)) fail(`${field} as a number must be integer cents`);
    return value;
  }
  if (typeof value !== 'string') fail(`${field} must be a string or integer cents`);

  const text = value.trim();
  // Whitespace inside the number means the input is malformed or uses a
  // convention we have not been told about. Either way the honest answer is to
  // refuse and ask, not to strip it out and produce a confident wrong figure.
  if (/\s/.test(text.replace(/^\(|\)$/g, '').trim())) {
    fail(`${field} contains embedded whitespace and is ambiguous: ${value}`);
  }
  // Accept accounting-style negatives, (1,234.56), alongside -$1,234.56.
  const parenthesised = /^\((.*)\)$/.exec(text);
  const inner = (parenthesised ? parenthesised[1] : text).trim();
  const normalised = inner.replace(/[$,]/g, '');
  const match = /^(-?)(\d+)(?:\.(\d{1,2}))?$/.exec(normalised);
  if (!match) fail(`${field} is not a recognisable money value: ${value}`);

  const [, sign, whole, fraction = ''] = match;
  const cents = Number(whole) * 100 + Number(fraction.padEnd(2, '0'));
  const negative = parenthesised || sign === '-';
  return negative ? -cents : cents;
}

function formatMoney(cents) {
  if (!Number.isInteger(cents)) fail('formatMoney requires integer cents');
  const negative = cents < 0;
  const abs = Math.abs(cents);
  const text = `$${Math.floor(abs / 100).toLocaleString('en-US')}.${String(abs % 100).padStart(2, '0')}`;
  return negative ? `-${text}` : text;
}

// Filename form of an amount: USD1284-99, or NEG1284-99 when it is a refund or
// credit. Keeping the sign readable in the name means a credit cannot be
// mistaken for a charge while scanning a folder.
function encodeAmount(cents) {
  if (cents === null || cents === undefined) return NO_AMOUNT;
  if (!Number.isInteger(cents)) fail('amount must be integer cents');
  const abs = Math.abs(cents);
  return `${cents < 0 ? 'NEG' : 'USD'}${Math.floor(abs / 100)}-${String(abs % 100).padStart(2, '0')}`;
}

function decodeAmount(token) {
  if (token === NO_AMOUNT) return null;
  const match = /^(USD|NEG)(\d+)-(\d{2})$/.exec(token);
  if (!match) fail(`amount token is malformed: ${token}`);
  const cents = Number(match[2]) * 100 + Number(match[3]);
  return match[1] === 'NEG' ? -cents : cents;
}

function normalizeExtension(value) {
  if (typeof value !== 'string') fail('extension must be a string');
  const ext = value.trim().toLowerCase().replace(/^\./, '');
  if (!/^[a-z0-9]{1,8}$/.test(ext)) fail(`extension is not usable: ${value}`);
  return ext;
}

/**
 * The canonical document record. Everything downstream — naming, filing,
 * reconciliation, the CPA packet — reads this shape.
 */
function normalizeDocument(input) {
  if (!input || Object.getPrototypeOf(input) !== Object.prototype) {
    fail('document must be an object');
  }
  const date = requireDate(input.date, 'date');
  const doc = {
    date,
    taxYear: input.taxYear === undefined ? Number(date.slice(0, 4)) : Number(input.taxYear),
    entity: slug(input.entity, 'entity', { maxLength: 24 }).toUpperCase(),
    docType: input.docType,
    counterparty: slug(input.counterparty, 'counterparty'),
    amountCents: input.amountCents === undefined || input.amountCents === null
      ? null
      : parseMoney(input.amountCents, 'amountCents'),
    reference: input.reference
      ? slug(input.reference, 'reference', { maxLength: 32, canonicalCase: false })
      : null,
    extension: normalizeExtension(input.extension ?? 'pdf'),
  };

  if (!DOC_TYPES.includes(doc.docType)) {
    fail(`docType must be one of: ${DOC_TYPES.join(', ')}`);
  }
  if (!Number.isInteger(doc.taxYear) || doc.taxYear < 1990 || doc.taxYear > 2100) {
    fail(`taxYear is out of range: ${input.taxYear}`);
  }
  return doc;
}

function buildFileName(input) {
  const doc = normalizeDocument(input);
  const parts = [
    doc.date,
    doc.entity,
    doc.docType,
    doc.counterparty,
    encodeAmount(doc.amountCents),
    doc.reference ?? NO_REFERENCE,
  ];
  return `${parts.join(FIELD_SEPARATOR)}.${doc.extension}`;
}

/**
 * Recover the record from the name. This is what makes a filed archive
 * queryable without a database: the folder itself is the index.
 */
function parseFileName(fileName) {
  if (typeof fileName !== 'string') fail('fileName must be a string');
  const lastDot = fileName.lastIndexOf('.');
  if (lastDot <= 0) fail(`fileName has no extension: ${fileName}`);

  const stem = fileName.slice(0, lastDot);
  const extension = normalizeExtension(fileName.slice(lastDot + 1));
  const parts = stem.split(FIELD_SEPARATOR);
  if (parts.length !== 6) {
    fail(`fileName does not follow the convention (expected 6 fields, found ${parts.length}): ${fileName}`);
  }

  const [date, entity, docType, counterparty, amountToken, referenceToken] = parts;
  if (!DOC_TYPES.includes(docType)) fail(`unknown docType in fileName: ${docType}`);

  return {
    date: requireDate(date, 'date'),
    taxYear: Number(date.slice(0, 4)),
    entity,
    docType,
    counterparty,
    amountCents: decodeAmount(amountToken),
    reference: referenceToken === NO_REFERENCE ? null : referenceToken,
    extension,
  };
}

/**
 * Where the document lives. Sorting by tax year at the top level is what makes
 * "send the CPA everything for 2025" a folder copy instead of a project.
 */
function buildFolderPath(input, { root = 'Finance' } = {}) {
  const doc = normalizeDocument(input);
  const bucket = DOC_TYPE_FOLDERS[doc.docType];
  return [root, String(doc.taxYear), doc.entity, bucket].join('/');
}

function buildFullPath(input, options) {
  return `${buildFolderPath(input, options)}/${buildFileName(input)}`;
}

/**
 * Check an existing archive against the convention.
 *
 * Returns per-file findings rather than throwing, because the point of running
 * it is to get the full list of what needs renaming in one pass.
 */
function auditPaths(paths, options = {}) {
  if (!Array.isArray(paths)) fail('paths must be an array');
  const findings = [];
  const seen = new Map();

  for (const fullPath of paths) {
    if (typeof fullPath !== 'string' || !fullPath.trim()) {
      findings.push({ path: String(fullPath), ok: false, issue: 'not a usable path', suggestion: null });
      continue;
    }
    const fileName = fullPath.slice(fullPath.lastIndexOf('/') + 1);
    let record;
    try {
      record = parseFileName(fileName);
    } catch (error) {
      findings.push({ path: fullPath, ok: false, issue: error.message, suggestion: null });
      continue;
    }

    const expected = buildFullPath(record, options);
    if (expected !== fullPath) {
      findings.push({
        path: fullPath,
        ok: false,
        issue: 'filed in the wrong folder for its own metadata',
        suggestion: expected,
      });
      continue;
    }

    // Same vendor, same day, same amount, filed twice: either a duplicate
    // upload or a genuine second charge. Both need a human to look, so both get
    // reported rather than silently deduplicated.
    const key = `${record.date}|${record.entity}|${record.counterparty}|${record.amountCents}`;
    if (seen.has(key)) {
      findings.push({
        path: fullPath,
        ok: false,
        issue: `possible duplicate of ${seen.get(key)} — same vendor, date and amount`,
        suggestion: null,
      });
      continue;
    }
    seen.set(key, fullPath);
    findings.push({ path: fullPath, ok: true, issue: null, suggestion: null });
  }
  return findings;
}

module.exports = {
  TaxonomyError,
  DOC_TYPES,
  DOC_TYPE_FOLDERS,
  FIELD_SEPARATOR,
  slug,
  parseMoney,
  formatMoney,
  encodeAmount,
  decodeAmount,
  normalizeDocument,
  buildFileName,
  parseFileName,
  buildFolderPath,
  buildFullPath,
  auditPaths,
};
